### ISSUE TITLE
Release v0.6.4

### ISSUE THREAD

**Issue by ajoubertza** [ska-sa/katcp-python#207]
This is just to inform users that a new minor release is planned. MeerKAT Control and Monitoring are the group most in need of this.  It fixes some memory leak issues. 

Question:  a new method was added for clients, `until_stopped`.  Should we bump to v0.7.0 rather than v0.6.4?

- [x] Read steps in the How to Contribute docs for making a release
- [x] Edit the changelog and release notes files
- [x] Make sure Jenkins tests are still passing on master branch
- [x] Make sure the documentation is updated for master (readthedocs)
- [x] Create a release tag on GitHub, from master branch
- [x] Make sure the documentation is updated for release (readthedocs)
- [x] Upload the new version to PyPI
- [x] Fill the release description on GitHub
- [x] Close this issue

**Comment by bmerry** [comment]
> Should we bump to v0.7.0 rather than v0.6.4?

I guess it depends what the versioning policy is. If you're following SemVer, it says
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

That would make 0.6.4 acceptable. It looks like other 0.6.* releases have also added new functionality.

**Comment by ajoubertza** [comment]
Thanks, @bmerry.  I'll use 0.6.4 in that case.  Could go to 0.7.0 for the bulk sensor sampling.
  
(first commit to this repo was in 2008, so I wonder when we'll be done with the "initial development"?! 🙂 )

**Comment by ajoubertza** [comment]
v0.6.4 release completed.
(I notice that PyPI shows no detailed info about the project, and hasn't for the last few versions - something to fix)
