### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by mmphego** [ska-sa/katcp-python#221]
This is just to inform users that a new minor release is planned. This release adds PY3 compatibility. 

- [x] Read steps in the How to Contribute docs for making a release
- [x] Edit the changelog and release notes files
- [x] Make sure Jenkins tests are still passing on `master` branch
- [x] Make sure the documentation is updated for `master` (readthedocs)
- [x] Create a release tag on GitHub, from `master` branch
- [x] Make sure the documentation is updated for release (readthedocs)
- [x] Upload the new version to PyPI
- [x] Fill the release description on GitHub
- [x] Close this issue

**Comment by ajoubertza** [comment]
@mmphego We may as well make this the actual release - having a "pre-release" issue seems unnecessary.  Just go straight to 0.7.0.  We can test it on test.pypi.org.  If there are further issues with 0.7.0 after that, then we do 0.7.1.

**Comment by mmphego** [comment]
Sounds :+1: with me, will update the PR
