### ISSUE TITLE
Tornado version

### ISSUE THREAD

**Issue by wfarah** [ska-sa/katcp-python#238]
Hi. I noticed that the `tornado` package requirement for `katcp` is restricted to versions between 4.3 and 5 in the `setup.py` script. `Jupyter-notebooks`, for example, require version 6.x. I tried `katcp` with `tornado` version 6 and it seems to work in my case, but do you think I might bump into issues in the future?

**Comment by tockards** [comment]
Hi @wfarah 

The `tornado` package restriction is needed as `katcp-python` is compatible in both Python 2 and Python 3 and `tornado` versions between 4.3 and 5 work well in Python 2 &3 with the existing code base and tests. 

**You will bump into issues** with `katcp-python` and versions of `tornado >= 5`.

If you would like see what issues you will bump into try the following. Create a python virtual environment and install `katcp-python` and its test requirements. Then upgrade your version of tornado and execute the tests for `katcp-python`. To execute the tests you can just use `python setup.py test`. Alternatively you can use tox. 

hope this helps.

**Comment by wfarah** [comment]
Hi @tockards 

Thanks for your reply.
Yes, I saw a failure mode right after posting this. I guess the solution here would be to use older versions of other packages that would be compatible with `tornado` <5.0. I'll close this issue.

Thanks!
