### ISSUE TITLE
Consider dropping support for Python 2.7

### ISSUE THREAD

**Issue by kiranshila** [ska-sa/katcp-python#257]
In a few months, Python 2.7 will have been officially deprecated for three years. By supporting python 2.7 (and really, I mean by restricting the version of tornado to be <5), this project is missing out on years of improvements in the language and ecosystem. This includes not only performance enhancements but also patches for security vulnerabilities. 

Not only that, but tools that also use tornado are not compatible with the pinned version (such as Jupyter), and it makes for an incredibly frustrating developer experience trying to find the right combination of old versions that make everything work.

By updating to the latest version of tornado (which seems to work fine in my tests), you enable this package and all downstream packages (like casperfpga) to "just work" with standard, modern python. In fact, the project could drop tornado altogether and use the native asyncio in python 3.

**Comment by bmerry** [comment]
@kiranshila I'm not directly involved in this repo so can't comment on why it pins an old Tornado version, but if you're looking for an asyncio-friendly implementation of the protocol, you might be interested in [aiokatcp](https://aiokatcp.readthedocs.io/en/latest/). It was developed independently of this repo so it's a very different API and not a drop-in replacement.

**Comment by kiranshila** [comment]
@bmerry This is great to see! I wonder if I should push the CASPER folks to consider switching to this.

**Comment by lanceWilliams** [comment]
@kiranshila This is certainly our intention eventually. At the moment though, this repo is a dependency of a large legacy code base that we are still in the process of migrating to Python 3. This legacy code base has a number of critical functions so we have to proceed with caution, which unfortunately makes the migration process slow and arduous. Once it is complete though, we do hope to fast forward all required packages while also doing some much needed design revisits along the way.
