### ISSUE TITLE
Fix deprecations

### ISSUE THREAD

**Issue by kiranshila** [ska-sa/katcp-python#262]
Attempting to use this library from the "current" (as of 2020) python version of 3.9 will not work due to some stdlib changes, as noted by deprecation warnings when running under python 3.8.

Specifically:
https://github.com/ska-sa/katcp-python/blob/080e7f2512711b85b8c4ed44e8f8e454a268fac2/katcp/resource_client.py#L1604
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

and

https://github.com/ska-sa/katcp-python/blob/080e7f2512711b85b8c4ed44e8f8e454a268fac2/katcp/kattypes.py#L893
```
DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
|     raw_handler._orig_argnames = inspect.getargspec(handler)[0]
```

**Comment by tockards** [comment]
Hi @kiranshila,

Thank you for the heads up as I had planned to run our tests against python 3.9 but that required some changes to our CI/CD images to accommodate for Python 3.9. 

The changes have been made and below is a branch that addresses this: 
https://github.com/ska-sa/katcp-python/tree/user/tockards/add-py39-for-tests 

I plan to open a PR before the end of the week.

**Comment by tockards** [comment]
@kiranshila The latest version of katcp-python works with Python 3.9. Could you possibly check/continue with what you were doing in python 3.9 with katcp-python and if you are happy we can close this issue.

**Comment by kiranshila** [comment]
These seem to be fixed, thanks!
